/**
 * mockData.ts — Realistic mock data for the Notifications Center
 */

import type { Notification, NotificationPreferences } from './types';

// ─── Mock Notifications ───────────────────────────────────────────────────────

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: 'n-001',
    category: 'rights-warning',
    priority: 'critical',
    title: 'Rights Conflict Detected',
    description: 'Clip "Skyline_Timelapse_4K.mov" in reel sequence may violate Getty Images license. Immediate review required before export.',
    projectName: 'Product Launch Video',
    projectColor: '#EC4899',
    actor: { name: 'Rights Sentinel AI', avatar: 'RS', avatarColor: '#EF4444' },
    timestamp: '3 min ago',
    timestampISO: '2024-06-14T09:57:00Z',
    isRead: false,
    meta: { clipName: 'Skyline_Timelapse_4K.mov', licenseType: 'Getty RF', risk: 'High' },
  },
  {
    id: 'n-002',
    category: 'approval-request',
    priority: 'high',
    title: 'Final Cut Awaiting Your Approval',
    description: 'Rami Al-Farsi submitted "Brand Refresh – Episode 3 Final Cut v2" for approval. 2 reviewers have already signed off.',
    projectName: 'Brand Refresh Campaign',
    projectColor: '#8B5CF6',
    actor: { name: 'Rami Al-Farsi', avatar: 'RF', avatarColor: '#F97316' },
    timestamp: '18 min ago',
    timestampISO: '2024-06-14T09:42:00Z',
    isRead: false,
    meta: { version: 'v2', reviewers: '2/3 approved', duration: '4:32' },
  },
  {
    id: 'n-003',
    category: 'ai-agent',
    priority: 'normal',
    title: 'Research Agent: Task Complete',
    description: 'Insight Engine completed deep research on "Q4 Consumer Behavior in GCC Markets". 47 sources verified, 12-page report ready.',
    projectName: 'Social Campaign Sprint',
    projectColor: '#06B6D4',
    actor: { name: 'Insight Engine', avatar: 'IE', avatarColor: '#8B5CF6' },
    timestamp: '32 min ago',
    timestampISO: '2024-06-14T09:28:00Z',
    isRead: false,
    meta: { sources: '47 verified', pages: '12', topic: 'Q4 GCC Consumer Behavior' },
  },
  {
    id: 'n-004',
    category: 'mention',
    priority: 'normal',
    title: 'Layla Hassan mentioned you',
    description: '@you — "Can you review the hook variants I drafted for the Viral Shorts? Trying to decide between Option A and C before EOD."',
    projectName: 'Viral Shorts Series',
    projectColor: '#F59E0B',
    actor: { name: 'Layla Hassan', avatar: 'LH', avatarColor: '#EC4899' },
    timestamp: '45 min ago',
    timestampISO: '2024-06-14T09:15:00Z',
    isRead: false,
    meta: { thread: 'Hook Variants Discussion', replies: '3' },
  },
  {
    id: 'n-005',
    category: 'deadline',
    priority: 'high',
    title: 'Deadline in 4 Hours — Script Due',
    description: '"Influencer Series Ep.7 Script" final draft is due at 2:00 PM today. Ziad Mansour has completed 80% of the draft.',
    projectName: 'Influencer Series',
    projectColor: '#F97316',
    actor: { name: 'Ziad Mansour', avatar: 'ZM', avatarColor: '#10B981' },
    timestamp: '1 hr ago',
    timestampISO: '2024-06-14T09:00:00Z',
    isRead: true,
    meta: { dueAt: '2:00 PM today', progress: '80%', assignee: 'Ziad Mansour' },
  },
  {
    id: 'n-006',
    category: 'assignment',
    priority: 'normal',
    title: 'New Task Assigned to You',
    description: 'Ayesha Rahman assigned you "Q3 Brand Voice Audit" on Social Campaign Sprint. Due Friday, June 21.',
    projectName: 'Social Campaign Sprint',
    projectColor: '#06B6D4',
    actor: { name: 'Ayesha Rahman', avatar: 'AR', avatarColor: '#3B82F6' },
    timestamp: '2 hrs ago',
    timestampISO: '2024-06-14T08:00:00Z',
    isRead: true,
    meta: { taskName: 'Q3 Brand Voice Audit', dueDate: 'June 21, 2024', assignedBy: 'Ayesha Rahman' },
  },
  {
    id: 'n-007',
    category: 'source-verified',
    priority: 'low',
    title: 'Source Verification Complete',
    description: 'Dina Karimi verified 8 research sources for "Documentary Series – Historical Archive". All cleared for production use.',
    projectName: 'Documentary Series',
    projectColor: '#10B981',
    actor: { name: 'Dina Karimi', avatar: 'DK', avatarColor: '#06B6D4' },
    timestamp: '3 hrs ago',
    timestampISO: '2024-06-14T07:00:00Z',
    isRead: true,
    meta: { sources: '8', status: 'All Cleared', section: 'Historical Archive' },
  },
  {
    id: 'n-008',
    category: 'comment',
    priority: 'normal',
    title: 'Sara Al-Mutairi left a comment',
    description: 'On "Final Edit v2" at 02:14 — "The color grade on the B-roll looks inconsistent around this timestamp. Check against the reference LUT."',
    projectName: 'Brand Refresh Campaign',
    projectColor: '#8B5CF6',
    actor: { name: 'Sara Al-Mutairi', avatar: 'SM', avatarColor: '#84CC16' },
    timestamp: '4 hrs ago',
    timestampISO: '2024-06-14T06:00:00Z',
    isRead: true,
    meta: { timestamp: '02:14', file: 'Final Edit v2', type: 'Color Note' },
  },
  {
    id: 'n-009',
    category: 'publication-status',
    priority: 'normal',
    title: 'Episode 4 Published Successfully',
    description: 'Khalid Osman published "Documentary Series – Episode 4" to YouTube and TikTok. Initial engagement: 4.2K views in 1 hour.',
    projectName: 'Documentary Series',
    projectColor: '#10B981',
    actor: { name: 'Khalid Osman', avatar: 'KO', avatarColor: '#F59E0B' },
    timestamp: '5 hrs ago',
    timestampISO: '2024-06-14T05:00:00Z',
    isRead: true,
    meta: { platforms: 'YouTube, TikTok', views: '4.2K in 1hr', episode: 'Episode 4' },
  },
  {
    id: 'n-010',
    category: 'ai-agent',
    priority: 'normal',
    title: 'Copywriter AI: 5 Hook Variants Generated',
    description: 'Copywriter Agent completed hook generation for "Year-End Recap". Variants scored 78–94 on engagement prediction model.',
    projectName: 'Year-End Recap',
    projectColor: '#84CC16',
    actor: { name: 'Copywriter AI', avatar: 'CA', avatarColor: '#8B5CF6' },
    timestamp: '6 hrs ago',
    timestampISO: '2024-06-14T04:00:00Z',
    isRead: true,
    meta: { variants: '5', scoreRange: '78–94', model: 'Engagement Predictor v3' },
  },
  {
    id: 'n-011',
    category: 'approval-request',
    priority: 'high',
    title: 'Research Report Needs Approval',
    description: 'Dina Karimi submitted "Q4 Consumer Trends – GCC Market Analysis" for approval. 28 pages, 3 visualizations included.',
    projectName: 'Brand Refresh Campaign',
    projectColor: '#8B5CF6',
    actor: { name: 'Dina Karimi', avatar: 'DK', avatarColor: '#06B6D4' },
    timestamp: '7 hrs ago',
    timestampISO: '2024-06-14T03:00:00Z',
    isRead: false,
    meta: { pages: '28', visualizations: '3', submittedBy: 'Dina Karimi' },
  },
  {
    id: 'n-012',
    category: 'deadline',
    priority: 'critical',
    title: 'Overdue — Client Delivery Missed',
    description: '"Influencer Series – Ep.6 Final Cut" was due yesterday at 5:00 PM. Client has been notified. Immediate action required.',
    projectName: 'Influencer Series',
    projectColor: '#F97316',
    actor: { name: 'System', avatar: 'SY', avatarColor: '#EF4444' },
    timestamp: '1 day ago',
    timestampISO: '2024-06-13T17:00:00Z',
    isRead: false,
    meta: { overdueby: '19 hours', deliverable: 'Ep.6 Final Cut', impact: 'Client escalation' },
  },
  {
    id: 'n-013',
    category: 'assignment',
    priority: 'normal',
    title: 'Farah Nasser assigned you to a project',
    description: 'You have been added as Creative Lead on "Year-End Recap". Project kicks off Monday, June 17.',
    projectName: 'Year-End Recap',
    projectColor: '#84CC16',
    actor: { name: 'Farah Nasser', avatar: 'FN', avatarColor: '#F59E0B' },
    timestamp: '1 day ago',
    timestampISO: '2024-06-13T12:00:00Z',
    isRead: true,
    meta: { role: 'Creative Lead', kickoff: 'June 17, 2024', assignedBy: 'Farah Nasser' },
  },
  {
    id: 'n-014',
    category: 'mention',
    priority: 'high',
    title: 'Nour Saleh mentioned you in a decision',
    description: '@you — "Looping you in on the budget reallocation for Q3. Need your sign-off before I proceed with the vendor contracts."',
    projectName: 'Brand Refresh Campaign',
    projectColor: '#8B5CF6',
    actor: { name: 'Nour Saleh', avatar: 'NS', avatarColor: '#7C3AED' },
    timestamp: '1 day ago',
    timestampISO: '2024-06-13T10:00:00Z',
    isRead: true,
    meta: { context: 'Budget Reallocation Q3', urgency: 'Sign-off Required' },
  },
  {
    id: 'n-015',
    category: 'publication-status',
    priority: 'low',
    title: 'Scheduled Post Queued',
    description: '"Viral Shorts – Pack 3" is queued for publication on June 16 at 9:00 AM across Instagram Reels, TikTok, and YouTube Shorts.',
    projectName: 'Viral Shorts Series',
    projectColor: '#F59E0B',
    actor: { name: 'Khalid Osman', avatar: 'KO', avatarColor: '#F59E0B' },
    timestamp: '2 days ago',
    timestampISO: '2024-06-12T15:00:00Z',
    isRead: true,
    meta: { scheduledFor: 'June 16, 9:00 AM', platforms: 'Instagram, TikTok, YouTube Shorts', pack: 'Pack 3' },
  },
];

// ─── Default Preferences ──────────────────────────────────────────────────────

export const DEFAULT_PREFERENCES: NotificationPreferences = {
  assignments: true,
  mentions: true,
  aiAgents: true,
  approvals: true,
  deadlines: true,
  researchUpdates: true,
  publicationUpdates: false,
  emailDigest: true,
  pushNotifications: false,
  sound: false,
};
