/**
 * mockData.ts — Static mock data for the Project Overview page.
 */

import type { ProjectOverviewData } from './types';

const now = new Date();
const daysOut = (d: number) => new Date(now.getTime() + d * 86_400_000);
const daysAgo = (d: number) => new Date(now.getTime() - d * 86_400_000);
const hoursAgo = (h: number) => new Date(now.getTime() - h * 3_600_000);

export const MOCK_PROJECT_OVERVIEW: ProjectOverviewData = {
  id: 'proj-001',
  title: 'The Rise of AI in Healthcare',
  description:
    'An in-depth documentary-style YouTube series exploring how artificial intelligence is reshaping modern healthcare — from diagnostics to drug discovery.',
  thumbnailGradient: 'from-[#7C3AED] via-[#4F46E5] to-[#06B6D4]',
  platform: 'YouTube',
  duration: '12–18 min',
  targetAudience: 'Tech-savvy professionals, 28–45',
  owner: { name: 'Sara Khalid', initials: 'SK', color: '#8B5CF6' },
  deadline: daysOut(22),
  status: 'in-progress',
  overallProgress: 47,
  activePhaseId: 'research',

  // ── Phases ────────────────────────────────────────────────────────────────

  phases: [
    {
      id: 'strategy',
      label: 'Strategy',
      status: 'completed',
      completion: 100,
      responsible: { name: 'Sara Khalid', initials: 'SK', color: '#8B5CF6' },
      lastUpdated: '2d ago',
    },
    {
      id: 'research',
      label: 'Research',
      status: 'in-progress',
      completion: 68,
      responsible: { name: 'James Park', initials: 'JP', color: '#06B6D4' },
      blockingIssue: '4 sources need verification',
      lastUpdated: '1h ago',
    },
    {
      id: 'script',
      label: 'Script',
      status: 'in-progress',
      completion: 20,
      responsible: { name: 'Maria Reyes', initials: 'MR', color: '#10B981' },
      lastUpdated: '6h ago',
    },
    {
      id: 'assets',
      label: 'Assets',
      status: 'not-started',
      completion: 0,
      responsible: { name: 'Leon Wu', initials: 'LW', color: '#F59E0B' },
      lastUpdated: '—',
    },
    {
      id: 'editing',
      label: 'Editing',
      status: 'not-started',
      completion: 0,
      responsible: { name: 'Sara Khalid', initials: 'SK', color: '#8B5CF6' },
      lastUpdated: '—',
    },
    {
      id: 'review',
      label: 'Review',
      status: 'not-started',
      completion: 0,
      responsible: { name: 'James Park', initials: 'JP', color: '#06B6D4' },
      lastUpdated: '—',
    },
    {
      id: 'distribution',
      label: 'Distribution',
      status: 'not-started',
      completion: 0,
      responsible: { name: 'Maria Reyes', initials: 'MR', color: '#10B981' },
      lastUpdated: '—',
    },
    {
      id: 'performance',
      label: 'Performance',
      status: 'not-started',
      completion: 0,
      responsible: { name: 'Leon Wu', initials: 'LW', color: '#F59E0B' },
      lastUpdated: '—',
    },
  ],

  // ── Health metrics ────────────────────────────────────────────────────────

  healthMetrics: [
    {
      id: 'hm-overall',
      label: 'Project Health',
      score: 78,
      trend: 5,
      explanation: 'Strong progress across strategy and research phases.',
      status: 'good',
      color: '#10B981',
    },
    {
      id: 'hm-originality',
      label: 'Originality Score',
      score: 91,
      trend: 3,
      explanation: 'Unique angle confirmed vs. 340 comparable videos.',
      status: 'excellent',
      color: '#8B5CF6',
    },
    {
      id: 'hm-feasibility',
      label: 'Feasibility Score',
      score: 82,
      trend: -2,
      explanation: 'Timeline slightly tight — consider scope reduction.',
      status: 'good',
      color: '#3B82F6',
    },
    {
      id: 'hm-virality',
      label: 'Virality Potential',
      score: 74,
      trend: 12,
      explanation: 'AI in healthcare trending +270% this week.',
      status: 'good',
      color: '#F59E0B',
    },
    {
      id: 'hm-evidence',
      label: 'Evidence Coverage',
      score: 61,
      trend: -8,
      explanation: '4 of 18 claims still need source verification.',
      status: 'warning',
      color: '#EF4444',
    },
    {
      id: 'hm-assets',
      label: 'Asset Readiness',
      score: 15,
      trend: 0,
      explanation: 'Asset phase not yet started.',
      status: 'warning',
      color: '#F59E0B',
    },
    {
      id: 'hm-rights',
      label: 'Rights Risk',
      score: 88,
      trend: 2,
      explanation: 'One music track flagged — replacement suggested.',
      status: 'good',
      color: '#06B6D4',
    },
    {
      id: 'hm-progress',
      label: 'Overall Progress',
      score: 47,
      trend: 7,
      explanation: '47% complete — on track for deadline.',
      status: 'good',
      color: '#9D6CFF',
    },
  ],

  // ── Timeline ──────────────────────────────────────────────────────────────

  timeline: [
    {
      id: 'tl-1',
      actor: 'StrategyBot',
      actorType: 'ai',
      actorInitials: 'SB',
      actorColor: '#8B5CF6',
      action: 'completed analysis of',
      target: 'Strategy Phase — all objectives confirmed',
      timestamp: hoursAgo(2),
      category: 'strategy',
      iconName: 'CheckCircle2',
    },
    {
      id: 'tl-2',
      actor: 'ResearchOwl',
      actorType: 'ai',
      actorInitials: 'RO',
      actorColor: '#06B6D4',
      action: 'verified',
      target: '12 sources across 3 medical databases',
      timestamp: hoursAgo(4),
      category: 'research',
      iconName: 'BookOpen',
    },
    {
      id: 'tl-3',
      actor: 'ScriptGenius',
      actorType: 'ai',
      actorInitials: 'SG',
      actorColor: '#10B981',
      action: 'generated',
      target: 'Script v3 — 2,400 words, 3 acts',
      timestamp: hoursAgo(6),
      category: 'script',
      iconName: 'FileText',
    },
    {
      id: 'tl-4',
      actor: 'James Park',
      actorType: 'human',
      actorInitials: 'JP',
      actorColor: '#06B6D4',
      action: 'approved',
      target: 'Scene 8 — Hospital corridor sequence',
      timestamp: hoursAgo(8),
      category: 'review',
      iconName: 'CheckSquare',
    },
    {
      id: 'tl-5',
      actor: 'RightsAuditor',
      actorType: 'ai',
      actorInitials: 'RA',
      actorColor: '#EF4444',
      action: 'flagged',
      target: 'Background music track "Deep Pulse" — licensing conflict',
      timestamp: hoursAgo(10),
      category: 'asset',
      iconName: 'AlertTriangle',
    },
    {
      id: 'tl-6',
      actor: 'Sara Khalid',
      actorType: 'human',
      actorInitials: 'SK',
      actorColor: '#8B5CF6',
      action: 'updated',
      target: 'Project deadline — pushed 3 days to allow for research',
      timestamp: daysAgo(1),
      category: 'team',
      iconName: 'Calendar',
    },
    {
      id: 'tl-7',
      actor: 'ViralityTwin',
      actorType: 'ai',
      actorInitials: 'VT',
      actorColor: '#F59E0B',
      action: 'analysed',
      target: 'Audience retention curve — hook at 0:08 recommended',
      timestamp: daysAgo(1),
      category: 'strategy',
      iconName: 'TrendingUp',
    },
    {
      id: 'tl-8',
      actor: 'Maria Reyes',
      actorType: 'human',
      actorInitials: 'MR',
      actorColor: '#10B981',
      action: 'uploaded',
      target: 'Primary research PDF — "AI in Diagnostics 2024"',
      timestamp: daysAgo(2),
      category: 'research',
      iconName: 'Upload',
    },
  ],

  // ── Team ─────────────────────────────────────────────────────────────────

  team: [
    {
      id: 'tm-1',
      name: 'Sara Khalid',
      role: 'Project Owner',
      initials: 'SK',
      color: '#8B5CF6',
      assignedPhase: 'strategy',
      status: 'online',
      tasksOpen: 2,
    },
    {
      id: 'tm-2',
      name: 'James Park',
      role: 'Research Lead',
      initials: 'JP',
      color: '#06B6D4',
      assignedPhase: 'research',
      status: 'online',
      tasksOpen: 5,
    },
    {
      id: 'tm-3',
      name: 'Maria Reyes',
      role: 'Script Writer',
      initials: 'MR',
      color: '#10B981',
      assignedPhase: 'script',
      status: 'away',
      tasksOpen: 3,
    },
    {
      id: 'tm-4',
      name: 'Leon Wu',
      role: 'Asset Designer',
      initials: 'LW',
      color: '#F59E0B',
      assignedPhase: 'assets',
      status: 'offline',
      tasksOpen: 0,
    },
  ],

  // ── Approvals ─────────────────────────────────────────────────────────────

  approvals: [
    {
      id: 'ap-1',
      title: 'Script v3 Approval',
      description: 'Full script ready for stakeholder sign-off before asset creation begins.',
      requester: { name: 'ScriptGenius AI', initials: 'SG', color: '#10B981' },
      priority: 'high',
      dueDate: daysOut(2),
      status: 'pending',
      phase: 'script',
    },
    {
      id: 'ap-2',
      title: 'Asset Budget Review',
      description: 'Stock footage + music licensing estimated at $840. Approval required.',
      requester: { name: 'Leon Wu', initials: 'LW', color: '#F59E0B' },
      priority: 'medium',
      dueDate: daysOut(5),
      status: 'pending',
      phase: 'assets',
    },
    {
      id: 'ap-3',
      title: 'Final Review Sign-off',
      description: 'Edited video requires owner approval before distribution queue.',
      requester: { name: 'Sara Khalid', initials: 'SK', color: '#8B5CF6' },
      priority: 'critical',
      dueDate: daysOut(18),
      status: 'pending',
      phase: 'review',
    },
  ],

  // ── Recent files ──────────────────────────────────────────────────────────

  recentFiles: [
    {
      id: 'rf-1',
      name: 'AI-in-Diagnostics-2024.pdf',
      type: 'pdf',
      size: '4.2 MB',
      uploadedBy: { name: 'Maria Reyes', initials: 'MR', color: '#10B981' },
      uploadedAt: daysAgo(2),
      phase: 'research',
    },
    {
      id: 'rf-2',
      name: 'Script-v3-Final.docx',
      type: 'doc',
      size: '128 KB',
      uploadedBy: { name: 'ScriptGenius AI', initials: 'SG', color: '#10B981' },
      uploadedAt: hoursAgo(6),
      phase: 'script',
    },
    {
      id: 'rf-3',
      name: 'Strategy-Brief.pdf',
      type: 'pdf',
      size: '2.1 MB',
      uploadedBy: { name: 'StrategyBot', initials: 'SB', color: '#8B5CF6' },
      uploadedAt: daysAgo(3),
      phase: 'strategy',
    },
    {
      id: 'rf-4',
      name: 'Reference-Thumbnail-v1.png',
      type: 'image',
      size: '890 KB',
      uploadedBy: { name: 'Leon Wu', initials: 'LW', color: '#F59E0B' },
      uploadedAt: daysAgo(1),
      phase: 'assets',
    },
    {
      id: 'rf-5',
      name: 'Source-Verification-Report.csv',
      type: 'csv',
      size: '45 KB',
      uploadedBy: { name: 'ResearchOwl', initials: 'RO', color: '#06B6D4' },
      uploadedAt: hoursAgo(4),
      phase: 'research',
    },
  ],

  // ── AI Recommendations ────────────────────────────────────────────────────

  recommendations: [
    {
      id: 'rec-1',
      priority: 'urgent',
      title: 'Verify 4 remaining research sources',
      body: 'Evidence coverage is at 61%. 4 claims remain unsupported. This could affect credibility score before publication.',
      agent: { name: 'ResearchOwl', initials: 'RO', color: '#06B6D4' },
      action: 'Open Research Lab',
      phase: 'research',
    },
    {
      id: 'rec-2',
      priority: 'high',
      title: 'Add stronger opening hook',
      body: 'ViralityTwin predicts 38% higher retention if a question hook is added in the first 8 seconds of the video.',
      agent: { name: 'ViralityTwin', initials: 'VT', color: '#F59E0B' },
      action: 'Edit Script',
      phase: 'script',
    },
    {
      id: 'rec-3',
      priority: 'medium',
      title: 'Replace flagged music track',
      body: '"Deep Pulse" by AudioRex has a conflicting commercial license for YouTube monetization. 3 free alternatives ready.',
      agent: { name: 'RightsAuditor', initials: 'RA', color: '#EF4444' },
      action: 'Review Assets',
      phase: 'assets',
    },
    {
      id: 'rec-4',
      priority: 'medium',
      title: 'Refine target audience segment',
      body: 'Your current audience description is broad. Narrowing to "clinical practitioners and health-tech investors" could improve ad CPM by ~22%.',
      agent: { name: 'StrategyBot', initials: 'SB', color: '#8B5CF6' },
      action: 'Open Strategy Room',
      phase: 'strategy',
    },
    {
      id: 'rec-5',
      priority: 'low',
      title: 'Consider cross-posting to LinkedIn',
      body: 'B2B healthcare content performs 3× better on LinkedIn with this audience profile. Distribution plan update recommended.',
      agent: { name: 'StrategyBot', initials: 'SB', color: '#8B5CF6' },
      action: 'View Distribution',
      phase: 'distribution',
    },
  ],
};
