/**
 * mockData.ts — Realistic mock data for the Asset Room.
 *
 * ⚠️  SIMULATED DATA — Not live. Used for UI development only.
 */

import type { AssetRoomData, AssetCard, AlternativeOption, TimelineEvent } from './types';

// ─── Assets ───────────────────────────────────────────────────────────────────

const ASSETS: AssetCard[] = [
  {
    id: 'a1',
    title: 'Hospital Emergency Room — Night Corridor',
    category: 'stock-footage',
    thumbnailGradient: 'from-[#0F172A] via-[#1E293B] to-[#0F172A]',
    thumbnailIcon: '🎬',
    source: 'Shutterstock',
    creator: 'MedVisionPro',
    resolution: '4K UHD',
    aspectRatio: '16:9',
    durationSec: 18,
    fileSizeMb: 842,
    license: 'royalty-free',
    commercialUse: true,
    attributionRequired: false,
    rightsRisk: 'low',
    assignedSceneId: 'sc1',
    assignedSceneLabel: 'Scene 01 — ER Cold Open',
    status: 'approved',
    downloadStatus: 'downloaded',
    addedAt: '2025-01-16',
    tags: ['hospital', 'emergency', 'night', 'medical'],
    isPremium: true,
    estimatedCostUSD: 79,
    linkedScriptSections: ['Segment 1 — Hook', 'Segment 2 — Setup'],
    linkedScenes: ['Scene 01 — ER Cold Open'],
    usageRights: 'Full commercial broadcast rights included. Unlimited usage across all media.',
    licenseDetails: 'Royalty-Free Standard License. One-time purchase, perpetual use.',
    aiSuggestions: ['Consider an 8-second cut for the hook.', 'Colour grade toward cool tones to match brand palette.'],
  },
  {
    id: 'a2',
    title: 'AI Diagnostic Monitor — Close-up B-roll',
    category: 'original-shoot',
    thumbnailGradient: 'from-[#312E81] via-[#4338CA] to-[#1E1B4B]',
    thumbnailIcon: '📹',
    source: 'In-house Production',
    creator: 'CreativeMind Studio',
    resolution: '4K UHD',
    aspectRatio: '16:9',
    durationSec: 12,
    fileSizeMb: 420,
    license: 'proprietary',
    commercialUse: true,
    attributionRequired: false,
    rightsRisk: 'low',
    assignedSceneId: 'sc4',
    assignedSceneLabel: 'Scene 04 — AI Monitor Display',
    status: 'used',
    downloadStatus: 'downloaded',
    addedAt: '2025-01-18',
    tags: ['ai', 'monitor', 'diagnostic', 'close-up', 'technology'],
    isPremium: false,
    linkedScriptSections: ['Segment 3 — Hook: AI vs Radiologist'],
    linkedScenes: ['Scene 04 — AI Monitor Display', 'Scene 07 — AI Monitor Close-up'],
    usageRights: 'Original production asset — full rights owned by CreativeMind Studio.',
    licenseDetails: 'Proprietary — all rights reserved.',
    aiSuggestions: ['Add motion blur overlay to simulate data processing.', 'Pair with scan-line sound effect (a5).'],
  },
  {
    id: 'a3',
    title: 'Radiology: Side-by-Side Comparison Graphic',
    category: 'motion-graphic',
    thumbnailGradient: 'from-[#065F46] via-[#047857] to-[#064E3B]',
    thumbnailIcon: '📊',
    source: 'Motion Array',
    creator: 'HealthVisuals',
    resolution: '1920×1080',
    aspectRatio: '16:9',
    durationSec: 6,
    fileSizeMb: 58,
    license: 'royalty-free',
    commercialUse: true,
    attributionRequired: false,
    rightsRisk: 'low',
    assignedSceneId: 'sc2',
    assignedSceneLabel: 'Scene 02 — Radiologist Comparison',
    status: 'approved',
    downloadStatus: 'downloaded',
    addedAt: '2025-01-17',
    tags: ['motion-graphic', 'radiology', 'comparison', 'data-viz'],
    isPremium: true,
    estimatedCostUSD: 29,
    linkedScriptSections: ['Segment 7 — Retention Evidence'],
    linkedScenes: ['Scene 02 — Radiologist Comparison'],
    usageRights: 'Commercial broadcast license. No credit required.',
    licenseDetails: 'Royalty-Free Extended License.',
    aiSuggestions: ['Update data labels to match Lancet meta-analysis figures.'],
  },
  {
    id: 'a4',
    title: 'FDA Press Conference Footage — 2023',
    category: 'news-reference',
    thumbnailGradient: 'from-[#1E3A8A] via-[#1D4ED8] to-[#1E40AF]',
    thumbnailIcon: '📺',
    source: 'C-SPAN Archive',
    creator: 'C-SPAN',
    resolution: '1080p',
    aspectRatio: '16:9',
    durationSec: 45,
    fileSizeMb: 210,
    license: 'editorial-only',
    commercialUse: false,
    attributionRequired: true,
    rightsRisk: 'high',
    assignedSceneId: 'sc3',
    assignedSceneLabel: 'Scene 03 — FDA Stats Montage',
    status: 'shortlisted',
    downloadStatus: 'not-downloaded',
    addedAt: '2025-01-19',
    tags: ['fda', 'press', 'regulatory', 'editorial'],
    isPremium: false,
    linkedScriptSections: ['Segment 5 — Regulatory Landscape'],
    linkedScenes: ['Scene 03 — FDA Stats Montage'],
    usageRights: '⚠️ Editorial use only. NOT cleared for commercial broadcast. Requires legal clearance.',
    licenseDetails: 'Editorial Only — Public Affairs footage. Commercial use requires separate clearance.',
    attributionText: 'Source: C-SPAN © 2023. Used under editorial use provisions.',
    aiSuggestions: ['Request legal clearance before production commit.', 'Consider replacing with AI-generated regulatory graphic (see alternatives).'],
    notes: '⚠️ RIGHTS RISK: This asset is editorial-only and NOT cleared for commercial broadcast. Flag for legal review.',
  },
  {
    id: 'a5',
    title: 'Digital Interface — Scan Line Sound FX',
    category: 'sound-effect',
    thumbnailGradient: 'from-[#7C2D12] via-[#9A3412] to-[#78350F]',
    thumbnailIcon: '🔊',
    source: 'Freesound.org',
    creator: 'synthlab_user',
    aspectRatio: '1:1',
    durationSec: 3,
    fileSizeMb: 1.2,
    license: 'cc0',
    commercialUse: true,
    attributionRequired: false,
    rightsRisk: 'low',
    assignedSceneId: 'sc4',
    assignedSceneLabel: 'Scene 04 — AI Monitor Display',
    status: 'approved',
    downloadStatus: 'downloaded',
    addedAt: '2025-01-16',
    tags: ['sound-fx', 'digital', 'scan', 'tech'],
    isPremium: false,
    linkedScriptSections: ['Segment 3 — Hook'],
    linkedScenes: ['Scene 04 — AI Monitor Display'],
    usageRights: 'CC0 — No rights reserved. Free for any use including commercial.',
    licenseDetails: 'Creative Commons Zero (CC0).',
    aiSuggestions: ['Layer with room tone for more realistic ambience.'],
  },
  {
    id: 'a6',
    title: 'Lancet Study — Figure 1 Table Screenshot',
    category: 'report-screenshot',
    thumbnailGradient: 'from-[#064E3B] via-[#065F46] to-[#047857]',
    thumbnailIcon: '📋',
    source: 'The Lancet Digital Health',
    creator: 'Salim et al. 2024',
    resolution: '2400×1600',
    aspectRatio: '3:2',
    fileSizeMb: 3.4,
    license: 'rights-managed',
    commercialUse: false,
    attributionRequired: true,
    rightsRisk: 'medium',
    assignedSceneId: 'sc2',
    assignedSceneLabel: 'Scene 02 — Radiologist Comparison',
    status: 'shortlisted',
    downloadStatus: 'not-downloaded',
    addedAt: '2025-01-17',
    tags: ['lancet', 'study', 'table', 'screenshot', 'academic'],
    isPremium: false,
    linkedScriptSections: ['Segment 7 — Retention Evidence'],
    linkedScenes: ['Scene 02 — Radiologist Comparison'],
    usageRights: '⚠️ Academic publication screenshot. Fair use for educational documentary — verify with legal.',
    licenseDetails: 'Rights-Managed — Academic Copyright. Elsevier. Contact permissions@elsevier.com.',
    attributionText: 'Salim, M. et al. (2024). The Lancet Digital Health, Figure 1.',
    aiSuggestions: ['Recreate as original infographic to avoid rights issue.', 'Use data to create branded chart (see alternatives).'],
    notes: 'Confirm fair-use doctrine applies for documentary context before approving.',
  },
  {
    id: 'a7',
    title: 'Hospital Corridor Walk — Aerial Drone',
    category: 'stock-footage',
    thumbnailGradient: 'from-[#134E4A] via-[#115E59] to-[#0F766E]',
    thumbnailIcon: '🎬',
    source: 'Storyblocks',
    creator: 'AerialMedics',
    resolution: '4K UHD',
    aspectRatio: '16:9',
    durationSec: 24,
    fileSizeMb: 1120,
    license: 'royalty-free',
    commercialUse: true,
    attributionRequired: false,
    rightsRisk: 'low',
    assignedSceneId: 'sc6',
    assignedSceneLabel: 'Scene 06 — Surgery B-roll',
    status: 'approved',
    downloadStatus: 'downloaded',
    addedAt: '2025-01-16',
    tags: ['hospital', 'aerial', 'drone', 'corridor', 'wide-shot'],
    isPremium: true,
    estimatedCostUSD: 0,
    linkedScriptSections: ['Segment 6 — Surgery Arc'],
    linkedScenes: ['Scene 06 — Surgery B-roll'],
    usageRights: 'Storyblocks Unlimited Member License. Commercial broadcast included.',
    licenseDetails: 'Royalty-Free — Storyblocks Unlimited License.',
    aiSuggestions: ['Speed ramp at 0:08 for dramatic entry.'],
  },
  {
    id: 'a8',
    title: 'Minimalist Underscore — Documentary Mood',
    category: 'music',
    thumbnailGradient: 'from-[#581C87] via-[#6D28D9] to-[#4C1D95]',
    thumbnailIcon: '🎵',
    source: 'Artlist.io',
    creator: 'Yoav Alyagon',
    aspectRatio: '1:1',
    durationSec: 180,
    fileSizeMb: 12.8,
    license: 'royalty-free',
    commercialUse: true,
    attributionRequired: false,
    rightsRisk: 'low',
    assignedSceneId: 'sc1',
    assignedSceneLabel: 'Scene 01 — ER Cold Open',
    status: 'purchased',
    downloadStatus: 'downloaded',
    addedAt: '2025-01-15',
    tags: ['music', 'documentary', 'minimalist', 'underscore', 'piano'],
    isPremium: true,
    estimatedCostUSD: 0,
    linkedScriptSections: ['Segment 7 — Sound Direction'],
    linkedScenes: ['Scene 01 — ER Cold Open', 'Scene 02 — Setup'],
    usageRights: 'Artlist annual license — unlimited broadcast including YouTube monetisation.',
    licenseDetails: 'Royalty-Free — Artlist Music License. Unlimited content.',
    aiSuggestions: ['Loop 0:15–0:45 section for 90-second hook sequence.', 'Reduce to -8dB under narration.'],
  },
  {
    id: 'a9',
    title: 'World Map — AI Adoption Heatmap',
    category: 'chart',
    thumbnailGradient: 'from-[#164E63] via-[#155E75] to-[#0E7490]',
    thumbnailIcon: '🗺️',
    source: 'AI-Generated (Midjourney + Data Overlay)',
    creator: 'NarratorAI',
    resolution: '3840×2160',
    aspectRatio: '16:9',
    fileSizeMb: 8.6,
    license: 'ai-generated',
    commercialUse: true,
    attributionRequired: false,
    rightsRisk: 'medium',
    assignedSceneId: 'sc7',
    assignedSceneLabel: 'Scene 07 — Market Infographic',
    status: 'approved',
    downloadStatus: 'downloaded',
    addedAt: '2025-01-20',
    tags: ['map', 'ai-generated', 'heatmap', 'global', 'data-viz'],
    isPremium: false,
    linkedScriptSections: ['Segment 2 — Market Introduction'],
    linkedScenes: ['Scene 07 — Market Infographic'],
    usageRights: 'AI-generated — verify no unlicensed training data sources apply to final output.',
    licenseDetails: 'Midjourney Commercial License (Pro tier). Data overlay: original.',
    aiSuggestions: ['Animate heatmap reveal with Lottie or After Effects.', 'Add source attribution for data layer.'],
    notes: '⚠️ AI-generated asset. Verify Midjourney commercial terms before broadcast use.',
  },
  {
    id: 'a10',
    title: 'Dr. Eric Topol — Interview Setup Frame',
    category: 'interview',
    thumbnailGradient: 'from-[#1F2937] via-[#374151] to-[#111827]',
    thumbnailIcon: '🎙️',
    source: 'In-house Production',
    creator: 'CreativeMind Studio',
    resolution: '4K UHD',
    aspectRatio: '16:9',
    durationSec: 342,
    fileSizeMb: 12400,
    license: 'proprietary',
    commercialUse: true,
    attributionRequired: true,
    rightsRisk: 'low',
    assignedSceneId: 'sc4',
    assignedSceneLabel: 'Scene 04 — Interview: Dr. Topol',
    status: 'used',
    downloadStatus: 'downloaded',
    addedAt: '2025-01-14',
    tags: ['interview', 'dr-topol', 'expert', 'talking-head'],
    isPremium: false,
    linkedScriptSections: ['Segment 3 — Expert Critique'],
    linkedScenes: ['Scene 04 — Interview: Dr. Topol'],
    usageRights: 'Signed release on file. Commercial documentary use approved.',
    licenseDetails: 'Proprietary — Subject release signed 2025-01-14.',
    attributionText: 'Dr. Eric Topol, Director, Scripps Research Translational Institute.',
    aiSuggestions: ['Cut to 90s for documentary edit.', 'Sync with B-roll at key quote moments.'],
  },
  {
    id: 'a11',
    title: 'Healthcare Market Bar Chart — $22B → $187B',
    category: 'chart',
    thumbnailGradient: 'from-[#78350F] via-[#92400E] to-[#B45309]',
    thumbnailIcon: '📈',
    source: 'AI-Generated (Internal)',
    creator: 'NarratorAI + DataBot',
    resolution: '1920×1080',
    aspectRatio: '16:9',
    fileSizeMb: 2.1,
    license: 'ai-generated',
    commercialUse: true,
    attributionRequired: false,
    rightsRisk: 'low',
    assignedSceneId: 'sc7',
    assignedSceneLabel: 'Scene 07 — Market Infographic',
    status: 'approved',
    downloadStatus: 'downloaded',
    addedAt: '2025-01-20',
    tags: ['chart', 'market', 'bar-chart', 'ai-generated', 'data'],
    isPremium: false,
    linkedScriptSections: ['Segment 2 — Market Introduction'],
    linkedScenes: ['Scene 07 — Market Infographic'],
    usageRights: 'Internally generated asset — full rights owned by CreativeMind Studio.',
    licenseDetails: 'Proprietary — internally generated.',
    aiSuggestions: ['Animate bars with 0.8s ease-in.'],
  },
  {
    id: 'a12',
    title: 'Fitzpatrick Scale Comparison — Skin Tone Bias',
    category: 'image',
    thumbnailGradient: 'from-[#7C2D12] via-[#9A3412] to-[#C2410C]',
    thumbnailIcon: '🖼️',
    source: 'Nature Medicine / Elsevier',
    creator: 'Daneshjou et al. 2022',
    resolution: '2000×1200',
    aspectRatio: '5:3',
    fileSizeMb: 4.8,
    license: 'rights-managed',
    commercialUse: false,
    attributionRequired: true,
    rightsRisk: 'high',
    assignedSceneId: 'sc5',
    assignedSceneLabel: 'Scene 05 — Bias Data Vis',
    status: 'rejected',
    downloadStatus: 'not-downloaded',
    addedAt: '2025-01-18',
    tags: ['skin-tone', 'bias', 'fitzpatrick', 'academic', 'rights-risk'],
    isPremium: false,
    linkedScriptSections: ['Segment 8 — Ethical Considerations'],
    linkedScenes: ['Scene 05 — Bias Data Vis'],
    usageRights: '🚫 REJECTED: Rights-managed academic figure. Not cleared for broadcast.',
    licenseDetails: 'Rights-Managed — Nature Publishing Group. Requires license purchase.',
    attributionText: 'Daneshjou et al. (2022). Nature Medicine, Figure 2.',
    aiSuggestions: ['Create original illustrated infographic using same data (see alternatives).'],
    notes: 'REJECTED — Do not use. Replace with original infographic or licensed illustration.',
  },
  {
    id: 'a13',
    title: 'Stanford Operating Theatre — Overhead Drone',
    category: 'original-shoot',
    thumbnailGradient: 'from-[#1F2937] via-[#0F172A] to-[#020617]',
    thumbnailIcon: '🎬',
    source: 'Stanford Medical Center — Commissioned',
    creator: 'CreativeMind Studio',
    resolution: '4K UHD',
    aspectRatio: '16:9',
    durationSec: 55,
    fileSizeMb: 2800,
    license: 'proprietary',
    commercialUse: true,
    attributionRequired: false,
    rightsRisk: 'low',
    assignedSceneId: 'sc6',
    assignedSceneLabel: 'Scene 06 — Stanford Surgery',
    status: 'used',
    downloadStatus: 'downloaded',
    addedAt: '2025-01-14',
    tags: ['surgery', 'stanford', 'drone', 'overhead', 'operating-room'],
    isPremium: false,
    linkedScriptSections: ['Segment 6 — Surgery Outcome'],
    linkedScenes: ['Scene 06 — Stanford Surgery'],
    usageRights: 'Signed facility agreement on file. Commercial documentary use approved.',
    licenseDetails: 'Proprietary — Stanford facility use agreement.',
    aiSuggestions: ['Grade to warm tones to humanise the scene.', 'Add subtle heartbeat pulse on cut-in.'],
  },
  {
    id: 'a14',
    title: 'AI Illustration — Neural Network Brain',
    category: 'ai-generated',
    thumbnailGradient: 'from-[#2E1065] via-[#4C1D95] to-[#3B0764]',
    thumbnailIcon: '🤖',
    source: 'DALL-E 3 (OpenAI)',
    creator: 'NarratorAI',
    resolution: '3584×2016',
    aspectRatio: '16:9',
    fileSizeMb: 11.2,
    license: 'ai-generated',
    commercialUse: true,
    attributionRequired: false,
    rightsRisk: 'medium',
    status: 'suggested',
    downloadStatus: 'not-downloaded',
    addedAt: '2025-01-21',
    tags: ['ai-generated', 'neural-network', 'brain', 'illustration', 'digital-art'],
    isPremium: false,
    linkedScriptSections: ['Segment 1 — Hook'],
    linkedScenes: [],
    usageRights: 'DALL-E 3 commercial terms apply (OpenAI ToS). Review before broadcast.',
    licenseDetails: 'AI-Generated — OpenAI DALL-E 3. Commercial use subject to OpenAI usage policy.',
    aiSuggestions: ['Good for title card background.', 'Confirm OpenAI commercial use clause for broadcast.'],
    notes: '⚠️ AI-generated — verify commercial broadcast rights before final use.',
  },
  {
    id: 'a15',
    title: 'Archival — Early MRI Machine 1977',
    category: 'archival-footage',
    thumbnailGradient: 'from-[#292524] via-[#44403C] to-[#292524]',
    thumbnailIcon: '📼',
    source: 'Getty Images Archive',
    creator: 'Getty Historical',
    resolution: '1080p (upscaled)',
    aspectRatio: '4:3',
    durationSec: 35,
    fileSizeMb: 185,
    license: 'rights-managed',
    commercialUse: true,
    attributionRequired: true,
    rightsRisk: 'medium',
    assignedSceneId: 'sc2',
    assignedSceneLabel: 'Scene 02 — History of Medicine',
    status: 'purchased',
    downloadStatus: 'downloaded',
    addedAt: '2025-01-15',
    tags: ['archival', 'mri', '1977', 'historical', 'medical-history'],
    isPremium: true,
    estimatedCostUSD: 249,
    linkedScriptSections: ['Segment 2 — History Montage'],
    linkedScenes: ['Scene 02 — History of Medicine'],
    usageRights: 'Rights-Managed single-use broadcast license. One documentary, unlimited territory.',
    licenseDetails: 'Getty Rights-Managed License — Editorial Documentary. Invoice on file.',
    attributionText: 'Getty Images / Historical Archive. Used under license.',
    aiSuggestions: ['Apply film grain and sepia grade to emphasise age.', 'Aspect-ratio letterbox to maintain 4:3.'],
  },
];

// ─── Alternatives ─────────────────────────────────────────────────────────────

const ALTERNATIVES: Record<string, AlternativeOption[]> = {
  a4: [
    {
      id: 'alt-a4-1', type: 'ai-generation', label: 'AI-Generated Regulatory Graphic',
      description: 'DALL-E 3 or Midjourney motion graphic showing FDA approval process without using editorial footage.',
      estimatedQuality: 'good', costLabel: 'Free (API cost ~$0.08)', costLevel: 'free',
      recommendedUseCase: 'Replace editorial footage to eliminate rights risk entirely.',
      thumbnailGradient: 'from-[#2E1065] to-[#4C1D95]',
    },
    {
      id: 'alt-a4-2', type: 'motion-graphic', label: 'Branded Regulatory Timeline Graphic',
      description: 'Custom motion graphic showing FDA AI device approval counts with brand colours.',
      estimatedQuality: 'excellent', costLabel: '$200–400 motion graphic fee', costLevel: 'medium',
      recommendedUseCase: 'Premium replacement — fully branded, no rights risk.',
      thumbnailGradient: 'from-[#065F46] to-[#059669]',
    },
    {
      id: 'alt-a4-3', type: 'free-asset', label: 'FDA.gov Public Domain Screenshot',
      description: 'Use official FDA.gov website screenshot (public domain US government content).',
      estimatedQuality: 'fair', costLabel: 'Free — public domain', costLevel: 'free',
      recommendedUseCase: 'Quick replacement when budget is tight. Less visually dynamic.',
      thumbnailGradient: 'from-[#1E3A8A] to-[#2563EB]',
    },
  ],
  a6: [
    {
      id: 'alt-a6-1', type: 'original-filming', label: 'Re-create Chart as Original Infographic',
      description: 'Reproduce Lancet Table 3 data as a custom branded infographic using original data from the study.',
      estimatedQuality: 'excellent', costLabel: '$150 design fee', costLevel: 'low',
      recommendedUseCase: 'Preferred — avoids all rights issues and matches brand identity.',
      thumbnailGradient: 'from-[#065F46] to-[#059669]',
    },
    {
      id: 'alt-a6-2', type: 'ai-generation', label: 'AI-Recreated Data Visualisation',
      description: 'Use GPT-4V to recreate the chart data as an SVG-style animated chart.',
      estimatedQuality: 'good', costLabel: 'Free (API cost)', costLevel: 'free',
      recommendedUseCase: 'Fast replacement with acceptable quality for B-roll context.',
      thumbnailGradient: 'from-[#2E1065] to-[#4C1D95]',
    },
  ],
  a12: [
    {
      id: 'alt-a12-1', type: 'original-filming', label: 'Commission Original Bias Illustration',
      description: 'Commission a custom illustrated infographic showing Fitzpatrick scale vs AI performance — fully original.',
      estimatedQuality: 'excellent', costLabel: '$300–600 illustration fee', costLevel: 'medium',
      recommendedUseCase: 'Best option — avoids all academic copyright issues and allows brand styling.',
      thumbnailGradient: 'from-[#7C2D12] to-[#C2410C]',
    },
    {
      id: 'alt-a12-2', type: 'motion-graphic', label: 'Animated Bar Chart — Bias Data',
      description: 'Recreate F1 score data as animated branded bar chart using public study numbers (data is factual, not copyright).',
      estimatedQuality: 'excellent', costLabel: '$150 motion graphic', costLevel: 'low',
      recommendedUseCase: 'More dynamic than static image and clears all rights issues.',
      thumbnailGradient: 'from-[#1E40AF] to-[#2563EB]',
    },
  ],
};

// ─── Usage timeline ───────────────────────────────────────────────────────────

const TIMELINE: TimelineEvent[] = [
  { id: 'tl1',  assetId: 'a10', eventType: 'uploaded',  label: 'Dr. Topol Interview Uploaded',        detail: 'Raw interview footage (342s, 12.4 GB)',           timestamp: '2025-01-14 09:22', actor: 'Layla Hassan'   },
  { id: 'tl2',  assetId: 'a8',  eventType: 'purchased',  label: 'Music Track Purchased — Artlist',     detail: 'Artlist license activated for Yoav Alyagon track', timestamp: '2025-01-15 11:45', actor: 'Marco Vitali'   },
  { id: 'tl3',  assetId: 'a1',  eventType: 'uploaded',   label: 'ER Corridor Footage Imported',        detail: 'Shutterstock 4K download — 842MB',                 timestamp: '2025-01-16 14:30', actor: 'NarratorAI'     },
  { id: 'tl4',  assetId: 'a5',  eventType: 'uploaded',   label: 'Scan SFX Uploaded from Freesound',   detail: 'CC0 sound effect — 1.2MB',                         timestamp: '2025-01-16 14:32', actor: 'NarratorAI'     },
  { id: 'tl5',  assetId: 'a3',  eventType: 'uploaded',   label: 'Radiology Motion Graphic Added',     detail: 'Motion Array premium download',                    timestamp: '2025-01-17 10:15', actor: 'Layla Hassan'   },
  { id: 'tl6',  assetId: 'a1',  eventType: 'assigned',   label: 'ER Footage Linked to Scene 01',       detail: 'Assigned to Scene 01 — ER Cold Open',              timestamp: '2025-01-17 10:22', actor: 'Layla Hassan'   },
  { id: 'tl7',  assetId: 'a1',  eventType: 'approved',   label: 'ER Footage Approved',                 detail: 'Director approval — Scene 01 confirmed',           timestamp: '2025-01-17 15:00', actor: 'Marco Vitali'   },
  { id: 'tl8',  assetId: 'a15', eventType: 'purchased',  label: 'Getty Archival MRI Footage Purchased','detail': 'Rights-managed license — $249',                  timestamp: '2025-01-15 09:00', actor: 'Layla Hassan'   },
  { id: 'tl9',  assetId: 'a9',  eventType: 'uploaded',   label: 'AI Map Generated',                    detail: 'Midjourney + data overlay — 8.6MB',                timestamp: '2025-01-20 08:00', actor: 'NarratorAI'     },
  { id: 'tl10', assetId: 'a11', eventType: 'uploaded',   label: 'Market Bar Chart Generated',          detail: 'AI-generated infographic — 2.1MB',                 timestamp: '2025-01-20 08:05', actor: 'NarratorAI'     },
  { id: 'tl11', assetId: 'a2',  eventType: 'used',        label: 'AI Monitor B-roll Cut Into Timeline','detail': 'Scene 04 — first assembly cut',                   timestamp: '2025-01-21 13:10', actor: 'Layla Hassan'   },
  { id: 'tl12', assetId: 'a10', eventType: 'used',        label: 'Dr. Topol Interview Used',            detail: 'Scene 04 — 90s clip confirmed',                    timestamp: '2025-01-21 14:00', actor: 'Marco Vitali'   },
  { id: 'tl13', assetId: 'a12', eventType: 'uploaded',   label: 'Fitzpatrick Image Flagged',           detail: 'Rights risk detected — escalated to legal',        timestamp: '2025-01-18 11:00', actor: 'NarratorAI'     },
  { id: 'tl14', assetId: 'a12', eventType: 'exported',   label: 'Fitzpatrick Image REJECTED',          detail: 'Legal review: not cleared for commercial use',     timestamp: '2025-01-18 16:30', actor: 'Marco Vitali'   },
];

// ─── Category stats ───────────────────────────────────────────────────────────

function countByCategory(assets: AssetCard[]): Record<string, number> {
  const map: Record<string, number> = {};
  assets.forEach(a => { map[a.category] = (map[a.category] ?? 0) + 1; });
  return map;
}

// ─── Export ───────────────────────────────────────────────────────────────────

export const MOCK_ASSET_ROOM: AssetRoomData = {
  projectTitle: 'The Rise of AI in Healthcare',
  assets: ASSETS,
  alternatives: ALTERNATIVES,
  timeline: TIMELINE,
  categoryStats: countByCategory(ASSETS) as ReturnType<typeof countByCategory>,
};
