/**
 * mockData.ts — All static mock data for the Research Lab.
 *
 * ⚠️ SIMULATED DATA — Not live. Used for UI development and demonstration only.
 */

import type { ResearchLabData, Researcher } from './types';

// ─── Researchers ──────────────────────────────────────────────────────────────

const RESEARCHERS: Researcher[] = [
  { id: 'r1', name: 'ResearchBot',   initials: 'RB', color: '#8B5CF6', role: 'AI Research Agent',    isAi: true  },
  { id: 'r2', name: 'Layla Hassan',  initials: 'LH', color: '#06B6D4', role: 'Lead Researcher',       isAi: false },
  { id: 'r3', name: 'Marco Vitali',  initials: 'MV', color: '#10B981', role: 'Fact Checker',          isAi: false },
  { id: 'r4', name: 'FactAgent',     initials: 'FA', color: '#F59E0B', role: 'AI Fact-Check Agent',   isAi: true  },
  { id: 'r5', name: 'Aisha Ndoye',   initials: 'AN', color: '#EF4444', role: 'Medical Consultant',    isAi: false },
];

export const MOCK_RESEARCH_LAB: ResearchLabData = {
  projectTitle: 'The Rise of AI in Healthcare',

  // ── Research Questions ───────────────────────────────────────────────────

  questions: [
    {
      id: 'q1',
      question: 'What is the current FDA approval rate for AI diagnostic tools in the US?',
      subQuestions: [
        'How many AI tools received breakthrough device designation in 2023?',
        'What is the average approval timeline for AI vs. traditional diagnostics?',
      ],
      assignedResearcher: RESEARCHERS[0],
      status: 'verified',
      priority: 'critical',
      sourceCount: 6,
      deadline: '2025-02-10',
      createdAt: '2025-01-15',
      tags: ['FDA', 'regulation', 'approval'],
    },
    {
      id: 'q2',
      question: 'How accurate is AI in detecting early-stage cancer compared to radiologists?',
      subQuestions: [
        'Which cancer types show the highest AI detection accuracy?',
        'What is the false positive rate in AI mammography screening?',
      ],
      assignedResearcher: RESEARCHERS[1],
      status: 'in-progress',
      priority: 'critical',
      sourceCount: 4,
      deadline: '2025-02-14',
      createdAt: '2025-01-16',
      tags: ['cancer', 'radiology', 'accuracy'],
    },
    {
      id: 'q3',
      question: 'What are the main ethical concerns raised by healthcare AI experts?',
      subQuestions: [
        'How does algorithmic bias affect underrepresented populations?',
        'What consent frameworks are emerging for AI-assisted diagnosis?',
      ],
      assignedResearcher: RESEARCHERS[4],
      status: 'needs-verification',
      priority: 'high',
      sourceCount: 3,
      deadline: '2025-02-18',
      createdAt: '2025-01-17',
      tags: ['ethics', 'bias', 'consent'],
    },
    {
      id: 'q4',
      question: 'What is the global market size of healthcare AI and projected growth by 2030?',
      subQuestions: [],
      assignedResearcher: RESEARCHERS[2],
      status: 'verified',
      priority: 'medium',
      sourceCount: 5,
      deadline: '2025-02-08',
      createdAt: '2025-01-14',
      tags: ['market', 'growth', 'investment'],
    },
    {
      id: 'q5',
      question: 'How is AI being used in drug discovery and clinical trials?',
      subQuestions: [
        'What is the cost reduction AI delivers in Phase I–III trials?',
      ],
      assignedResearcher: RESEARCHERS[0],
      status: 'to-research',
      priority: 'high',
      sourceCount: 0,
      deadline: '2025-02-25',
      createdAt: '2025-01-19',
      tags: ['drug discovery', 'pharma', 'trials'],
    },
    {
      id: 'q6',
      question: 'What patient outcomes have been documented after AI-assisted surgery?',
      subQuestions: [],
      assignedResearcher: RESEARCHERS[3],
      status: 'in-progress',
      priority: 'high',
      sourceCount: 2,
      deadline: '2025-02-20',
      createdAt: '2025-01-18',
      tags: ['surgery', 'outcomes', 'robotics'],
    },
    {
      id: 'q7',
      question: 'Which hospitals are leading in AI adoption and what are their measurable results?',
      subQuestions: [],
      assignedResearcher: RESEARCHERS[1],
      status: 'to-research',
      priority: 'medium',
      sourceCount: 0,
      deadline: '2025-03-01',
      createdAt: '2025-01-20',
      tags: ['hospitals', 'case-study', 'adoption'],
    },
    {
      id: 'q8',
      question: 'What are the reimbursement models for AI healthcare tools in the EU vs. US?',
      subQuestions: [],
      assignedResearcher: RESEARCHERS[2],
      status: 'rejected',
      priority: 'low',
      sourceCount: 1,
      deadline: '2025-02-28',
      createdAt: '2025-01-19',
      tags: ['reimbursement', 'policy', 'EU'],
    },
  ],

  // ── Source Cards ──────────────────────────────────────────────────────────

  sources: [
    {
      id: 's1',
      title: 'Artificial Intelligence in Radiology: 2023 FDA Approval Summary',
      publisher: 'U.S. Food & Drug Administration',
      author: 'FDA Center for Devices and Radiological Health',
      publicationDate: 'Oct 2023',
      sourceType: 'government',
      url: 'https://www.fda.gov/medical-devices/software-as-medical-device-samd/artificial-intelligence-and-machine-learning-aiml-enabled-medical-devices',
      relevantQuotation: 'As of October 2023, FDA has authorized 692 AI/ML-enabled medical devices, with radiology accounting for 75% of all approvals.',
      reportPage: 'p. 4',
      figureOrTableRef: 'Figure 1 — AI Device Approvals by Year',
      tier: 'primary',
      confidenceScore: 96,
      freshnessScore: 88,
      assignedResearcher: RESEARCHERS[0],
      verificationStatus: 'verified',
      linkedQuestionIds: ['q1'],
      notes: 'Official government source. Cross-referenced with Federal Register entries.',
      documentType: 'report',
      thumbnailGradient: 'from-[#1E40AF] via-[#1D4ED8] to-[#2563EB]',
    },
    {
      id: 's2',
      title: 'AI-Assisted Mammography Screening: A Meta-Analysis of 12 Randomised Controlled Trials',
      publisher: 'The Lancet Digital Health',
      author: 'Salim, M., Winkel, R., Mattsson, S., et al.',
      publicationDate: 'Jan 2024',
      sourceType: 'academic',
      url: 'https://www.thelancet.com/journals/landig/article/PIIS2589-7500(23)00235-X',
      relevantQuotation: 'AI screening systems demonstrated non-inferiority to double reading by two radiologists (sensitivity 81.0% vs 80.1%, specificity 77.4% vs 77.8%), with a 44% reduction in radiologist workload.',
      reportPage: 'p. 12',
      figureOrTableRef: 'Table 3 — Sensitivity/Specificity Comparison',
      tier: 'primary',
      confidenceScore: 92,
      freshnessScore: 95,
      assignedResearcher: RESEARCHERS[1],
      verificationStatus: 'verified',
      linkedQuestionIds: ['q2'],
      notes: 'Peer-reviewed. 2023 data. Highly credible for cancer detection claims.',
      documentType: 'academic',
      thumbnailGradient: 'from-[#065F46] via-[#047857] to-[#059669]',
    },
    {
      id: 's3',
      title: 'Global AI in Healthcare Market Report 2024–2030',
      publisher: 'Grand View Research',
      author: 'Grand View Research Analytics Team',
      publicationDate: 'Mar 2024',
      sourceType: 'company-report',
      url: 'https://www.grandviewresearch.com/industry-analysis/artificial-intelligence-ai-healthcare-market',
      relevantQuotation: 'The global AI in healthcare market size was valued at USD 22.45 billion in 2023 and is projected to grow at a CAGR of 36.1% from 2024 to 2030.',
      reportPage: 'p. 7',
      figureOrTableRef: 'Figure 2.1 — Market Size Forecast 2024–2030',
      tier: 'secondary',
      confidenceScore: 74,
      freshnessScore: 91,
      assignedResearcher: RESEARCHERS[2],
      verificationStatus: 'partially-supported',
      linkedQuestionIds: ['q4'],
      notes: 'Market research firm — methodology not fully disclosed. Cross-verify with McKinsey report.',
      documentType: 'report',
      thumbnailGradient: 'from-[#78350F] via-[#92400E] to-[#B45309]',
    },
    {
      id: 's4',
      title: 'Algorithmic Fairness in AI Diagnostics: Racial Bias in Dermatology AI Systems',
      publisher: 'Nature Medicine',
      author: 'Daneshjou, R., Vodrahalli, K., Novoa, R.A., et al.',
      publicationDate: 'May 2022',
      sourceType: 'academic',
      url: 'https://www.nature.com/articles/s41591-022-01774-3',
      relevantQuotation: 'Skin condition classification AI systems showed significantly lower performance (F1 score 0.49 vs 0.61) on darker skin tones, with three of nine systems failing to meet minimum performance thresholds for Fitzpatrick scale types V–VI.',
      reportPage: 'p. 6',
      figureOrTableRef: 'Table 2 — Performance by Fitzpatrick Scale',
      tier: 'primary',
      confidenceScore: 89,
      freshnessScore: 62,
      assignedResearcher: RESEARCHERS[4],
      verificationStatus: 'contested',
      linkedQuestionIds: ['q3'],
      notes: 'Contested: two subsequent studies (2023) show improved performance on newer models. Needs update citation.',
      documentType: 'pdf',
      thumbnailGradient: 'from-[#7C2D12] via-[#9A3412] to-[#C2410C]',
    },
    {
      id: 's5',
      title: 'AI in Drug Discovery: Reducing Clinical Trial Costs Through Machine Learning',
      publisher: 'McKinsey & Company',
      author: 'Olanrewaju, T., White, O., Chui, M.',
      publicationDate: 'Nov 2023',
      sourceType: 'institutional',
      url: 'https://www.mckinsey.com/industries/life-sciences/our-insights/ai-in-drug-discovery',
      relevantQuotation: 'AI-augmented drug discovery could reduce clinical trial costs by 30–50%, cutting the average time from target identification to first-in-human studies from 4.5 years to under 2 years.',
      reportPage: 'p. 14',
      figureOrTableRef: 'Exhibit 4 — AI Impact on R&D Timeline',
      tier: 'secondary',
      confidenceScore: 81,
      freshnessScore: 87,
      assignedResearcher: RESEARCHERS[0],
      verificationStatus: 'unverified',
      linkedQuestionIds: ['q5'],
      notes: 'Strong source but needs primary academic confirmation. Flag for fact-check.',
      documentType: 'report',
      thumbnailGradient: 'from-[#312E81] via-[#3730A3] to-[#4338CA]',
    },
    {
      id: 's6',
      title: 'Interview: Dr. Eric Topol on the Limits of AI in Clinical Practice',
      publisher: 'STAT News',
      author: 'Molteni, M.',
      publicationDate: 'Dec 2023',
      sourceType: 'interview',
      url: 'https://www.statnews.com/2023/12/14/eric-topol-ai-clinical-practice/',
      relevantQuotation: '"The problem is not whether AI can read a scan better than a radiologist in a controlled study — the problem is whether it can perform in the messy, real-world hospital environment with incomplete data, poor lighting, and patient motion artifacts."',
      reportPage: '',
      figureOrTableRef: '',
      tier: 'secondary',
      confidenceScore: 78,
      freshnessScore: 93,
      assignedResearcher: RESEARCHERS[1],
      verificationStatus: 'verified',
      linkedQuestionIds: ['q2', 'q3'],
      notes: 'Expert opinion. Cannot be used as sole statistical source. Useful for framing.',
      documentType: 'article',
      thumbnailGradient: 'from-[#134E4A] via-[#115E59] to-[#0F766E]',
    },
    {
      id: 's7',
      title: 'WHO Global Strategy on Digital Health 2020–2025: AI Applications',
      publisher: 'World Health Organization',
      author: 'World Health Organization Digital Health Division',
      publicationDate: 'Feb 2021',
      sourceType: 'government',
      url: 'https://www.who.int/docs/default-source/digital-health-documents/who-global-strategy-on-digital-health-2020-2025.pdf',
      relevantQuotation: 'Governments must establish national frameworks to ensure AI diagnostic tools undergo rigorous clinical validation before population-level deployment.',
      reportPage: 'p. 42',
      figureOrTableRef: '',
      tier: 'primary',
      confidenceScore: 88,
      freshnessScore: 44,
      assignedResearcher: RESEARCHERS[3],
      verificationStatus: 'outdated',
      linkedQuestionIds: ['q3', 'q1'],
      notes: '⚠️ Published 2021 — predates rapid AI adoption. Useful for policy framing only. Seek 2024 update.',
      documentType: 'pdf',
      thumbnailGradient: 'from-[#164E63] via-[#155E75] to-[#0E7490]',
    },
    {
      id: 's8',
      title: 'Robotic Surgery Outcomes: A 5-Year Retrospective Study at Stanford Medical Center',
      publisher: 'Journal of the American College of Surgeons',
      author: 'Park, J.H., Liu, X., Ramirez, C.A., et al.',
      publicationDate: 'Aug 2023',
      sourceType: 'academic',
      url: 'https://www.journalacs.org/article/S1072-7515(23)00412-5',
      relevantQuotation: 'AI-assisted laparoscopic procedures demonstrated a 23% reduction in post-operative complications and a 31% decrease in average surgery duration compared to conventional minimally invasive approaches.',
      reportPage: 'p. 8',
      figureOrTableRef: 'Figure 3 — Complication Rate by Procedure Type',
      tier: 'primary',
      confidenceScore: 91,
      freshnessScore: 90,
      assignedResearcher: RESEARCHERS[3],
      verificationStatus: 'verified',
      linkedQuestionIds: ['q6'],
      notes: 'Excellent source. Stanford IRB approved. Suitable for high-confidence claims.',
      documentType: 'pdf',
      thumbnailGradient: 'from-[#1F2937] via-[#111827] to-[#0F172A]',
    },
  ],

  // ── Documents ─────────────────────────────────────────────────────────────

  documents: [
    {
      id: 'd1',
      title: 'FDA AI Device Approval Summary 2023',
      documentType: 'pdf',
      thumbnailGradient: 'from-[#1E40AF] to-[#2563EB]',
      publisher: 'U.S. FDA',
      dateAdded: '2025-01-16',
      pageCount: 28,
      fileSize: '4.2 MB',
      sourceId: 's1',
    },
    {
      id: 'd2',
      title: 'Lancet Digital Health — Mammography AI Meta-Analysis',
      documentType: 'pdf',
      thumbnailGradient: 'from-[#065F46] to-[#059669]',
      publisher: 'The Lancet',
      dateAdded: '2025-01-17',
      pageCount: 16,
      fileSize: '2.1 MB',
      sourceId: 's2',
    },
    {
      id: 'd3',
      title: 'Grand View Research — Healthcare AI Market 2030',
      documentType: 'report',
      thumbnailGradient: 'from-[#78350F] to-[#B45309]',
      publisher: 'Grand View Research',
      dateAdded: '2025-01-18',
      pageCount: 84,
      fileSize: '8.7 MB',
      sourceId: 's3',
    },
    {
      id: 'd4',
      title: 'WHO Digital Health Strategy AI Extract',
      documentType: 'pdf',
      thumbnailGradient: 'from-[#164E63] to-[#0E7490]',
      publisher: 'World Health Organization',
      dateAdded: '2025-01-15',
      pageCount: 112,
      fileSize: '14.3 MB',
      sourceId: 's7',
    },
    {
      id: 'd5',
      title: 'Stanford Robotic Surgery Outcomes Dataset (CSV)',
      documentType: 'dataset',
      thumbnailGradient: 'from-[#1F2937] to-[#0F172A]',
      publisher: 'Stanford Medical Center',
      dateAdded: '2025-01-19',
      fileSize: '1.8 MB',
      sourceId: 's8',
    },
  ],

  // ── Evidence Map ──────────────────────────────────────────────────────────

  evidenceMap: {
    nodes: [
      { id: 'n1',  type: 'claim',                label: 'AI matches radiologist accuracy', subtitle: 'Main claim',                     x: 320, y:  60 },
      { id: 'n2',  type: 'primary-source',        label: 'Lancet Meta-Analysis',            subtitle: 'Sensitivity 81% vs 80.1%',       x: 120, y: 200 },
      { id: 'n3',  type: 'primary-source',        label: 'FDA Approval Summary',            subtitle: '692 AI devices approved',        x: 520, y: 200 },
      { id: 'n4',  type: 'supporting-source',     label: 'Dr. Eric Topol Interview',        subtitle: 'Expert endorsement',             x:  60, y: 340 },
      { id: 'n5',  type: 'supporting-source',     label: 'McKinsey AI Healthcare',          subtitle: 'Industry validation',            x: 220, y: 340 },
      { id: 'n6',  type: 'contradicting-source',  label: 'Nature Medicine — Bias Study',    subtitle: 'F1 score gap by skin tone',      x: 460, y: 340 },
      { id: 'n7',  type: 'script-usage',          label: 'Script Segment 3 — Hook',         subtitle: 'AI diagnosis opening scene',     x: 120, y: 480 },
      { id: 'n8',  type: 'script-usage',          label: 'Script Segment 7 — Evidence',     subtitle: 'Statistics narration',           x: 320, y: 480 },
      { id: 'n9',  type: 'scene-usage',           label: 'Scene 04 — Hospital corridor',    subtitle: 'B-roll AI monitor display',      x: 520, y: 480 },
      { id: 'n10', type: 'scene-usage',           label: 'Scene 09 — Radiologist desk',     subtitle: 'Side-by-side comparison',        x: 200, y: 600 },
    ],
    edges: [
      { id: 'e1',  source: 'n2',  target: 'n1',  label: 'supports'      },
      { id: 'e2',  source: 'n3',  target: 'n1',  label: 'supports'      },
      { id: 'e3',  source: 'n4',  target: 'n2',  label: 'corroborates'  },
      { id: 'e4',  source: 'n5',  target: 'n2',  label: 'corroborates'  },
      { id: 'e5',  source: 'n6',  target: 'n1',  label: 'contradicts'   },
      { id: 'e6',  source: 'n2',  target: 'n7',  label: 'cited in'      },
      { id: 'e7',  source: 'n1',  target: 'n8',  label: 'referenced in' },
      { id: 'e8',  source: 'n3',  target: 'n9',  label: 'visualised in' },
      { id: 'e9',  source: 'n2',  target: 'n10', label: 'visualised in' },
    ],
  },

  // ── Research Coverage ─────────────────────────────────────────────────────

  coverage: {
    coveragePercent:    68,
    verifiedSources:    4,
    pendingVerification: 2,
    evidenceQuality:    79,
    overallConfidence:  72,
    totalSources:       8,
  },

  // ── Researchers ───────────────────────────────────────────────────────────

  researchers: RESEARCHERS,
};
